<a href="https://colab.research.google.com/github/astitwa-agarwal12/Movie_Recommendation_System/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
movies_data = pd.read_csv('/content/movies.csv',error_bad_lines=False,engine="python")

Skipping line 1729: unexpected end of data


In [6]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [7]:
movies_data.shape

(1727, 24)

In [8]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [9]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [10]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [11]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
1722    Thriller Horror vampire dracula bite blood vla...
1723    Family Comedy based on novel job interview bad...
1724    Drama Romance bachelor beautiful prejudice sui...
1725    Science Fiction Drama Thriller artificial inte...
1726    Adventure scotland biography 18th century high...
Length: 1727, dtype: object


In [12]:
vectorizer = TfidfVectorizer()

In [13]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [16]:
print(feature_vectors)

  (0, 1160)	0.1681850883977992
  (0, 3832)	0.11845777041246705
  (0, 6403)	0.19297444794554108
  (0, 4991)	0.16360123773563218
  (0, 4292)	0.23498407363976623
  (0, 7188)	0.1588035054607688
  (0, 8188)	0.21118979500505486
  (0, 6899)	0.21480659896382445
  (0, 6535)	0.21884984179514655
  (0, 8510)	0.21884984179514655
  (0, 8384)	0.21884984179514655
  (0, 6552)	0.14968247700261542
  (0, 5620)	0.2525196383315525
  (0, 5462)	0.09386645692050875
  (0, 8380)	0.12134012455919724
  (0, 7514)	0.06968049479516267
  (0, 2420)	0.24264412042985792
  (0, 7011)	0.21480659896382445
  (0, 1540)	0.23498407363976623
  (0, 8143)	0.1242133350871461
  (0, 7062)	0.3191159898086201
  (0, 2897)	0.16360123773563218
  (0, 1462)	0.24264412042985792
  (0, 1777)	0.2525196383315525
  (0, 2663)	0.09512738921290718
  :	:
  (1726, 7217)	0.19785972638008756
  (1726, 1279)	0.18411987606681535
  (1726, 4293)	0.1792159112250296
  (1726, 1308)	0.1750696680297471
  (1726, 4643)	0.46371038452701513
  (1726, 815)	0.13419039849

In [31]:
feature_vectors.shape

(1727, 8524)

In [17]:
similarity = cosine_similarity(feature_vectors)

In [18]:
print(similarity)

[[1.         0.0638432  0.03416697 ... 0.00906097 0.0291076  0.0043353 ]
 [0.0638432  1.         0.02754379 ... 0.09529031 0.         0.00771916]
 [0.03416697 0.02754379 1.         ... 0.         0.         0.00458222]
 ...
 [0.00906097 0.09529031 0.         ... 1.         0.00871581 0.        ]
 [0.0291076  0.         0.         ... 0.00871581 1.         0.13589306]
 [0.0043353  0.00771916 0.00458222 ... 0.         0.13589306 1.        ]]


In [19]:
print(similarity.shape)

(1727, 1727)


In [30]:
similarity[0]

array([1.        , 0.0638432 , 0.03416697, ..., 0.00906097, 0.0291076 ,
       0.0043353 ])

In [20]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Iron man


In [21]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [22]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [23]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [24]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [25]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.02672161426174173), (1, 0.04986396079931407), (2, 0.01000826036048587), (3, 0.004803878488481836), (4, 0.025719002683506683), (5, 0.009893136012725033), (6, 0.08185065876322486), (7, 0.21650922967093625), (8, 0.005542704093598995), (9, 0.06386963822166346), (10, 0.063434644709376), (11, 0.008362179368558735), (12, 0.009896358629568162), (13, 0.00868098357711408), (14, 0.08199861878804651), (15, 0.005132454908910378), (16, 0.20870880803195604), (17, 0.009329591449020971), (18, 0.03825082920484583), (19, 0.07932570423224793), (20, 0.06470453778735946), (21, 0.008157934965945041), (22, 0.004972066272176751), (23, 0.004624391911182676), (24, 0.008448600177311343), (25, 0.0), (26, 0.19541480742952172), (27, 0.024890323553055857), (28, 0.05509636860933315), (29, 0.009893326230285417), (30, 0.0644443232924636), (31, 0.2929713662704675), (32, 0.0305271462690328), (33, 0.11049749733846907), (34, 0.0), (35, 0.028864729191817526), (36, 0.026223234499147274), (37, 0.005605677685552888), (38

In [26]:
len(similarity_score)

1727

In [27]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(68, 1.0), (79, 0.38176435314396423), (31, 0.2929713662704675), (7, 0.21650922967093625), (16, 0.20870880803195604), (26, 0.19541480742952172), (85, 0.18291374120479942), (182, 0.1671797373073459), (511, 0.14496408272544475), (64, 0.1279531407774603), (783, 0.12554790089714948), (203, 0.12499664857485335), (46, 0.12357980825071643), (174, 0.12192404984147595), (101, 0.11986096104259668), (131, 0.11962843246468666), (138, 0.11850141539279871), (169, 0.11613388492318913), (94, 0.11555561329314111), (1553, 0.11468981996922853), (126, 0.11273358032521127), (353, 0.11217791092424911), (788, 0.11192661362471894), (607, 0.11092522296521597), (33, 0.11049749733846907), (1451, 0.10995863187124394), (661, 0.1063943390565304), (1210, 0.10158867437287417), (720, 0.10120936326284599), (618, 0.09906168988546309), (954, 0.09790841780553458), (307, 0.09754215829948217), (1406, 0.09554522267631861), (800, 0.09431565919636355), (39, 0.09141964702912908), (38, 0.0913193560202922), (122, 0.08897337355730

In [28]:
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . X-Men: Apocalypse
11 . Mortdecai
12 . X2
13 . X-Men: Days of Future Past
14 . The Incredible Hulk
15 . X-Men: First Class
16 . G-Force
17 . The Last Airbender
18 . Captain America: The First Avenger
19 . Guardians of the Galaxy
20 . Se7en
21 . Thor: The Dark World
22 . Tropic Thunder
23 . Deadpool
24 . Sky Captain and the World of Tomorrow
25 . X-Men: The Last Stand
26 . Zoom
27 . Zathura: A Space Adventure
28 . Gothika
29 . Contagion


In [29]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Xmen
Movies suggested for you : 

1 . X-Men
2 . X2
3 . X-Men: The Last Stand
4 . X-Men: Days of Future Past
5 . X-Men: Apocalypse
6 . The Wolverine
7 . Avengers: Age of Ultron
8 . The Avengers
9 . Ant-Man
10 . X-Men Origins: Wolverine
11 . Iron Man 2
12 . Man of Steel
13 . The Incredible Hulk
14 . Thor: The Dark World
15 . Deadpool
16 . The Amazing Spider-Man 2
17 . X-Men: First Class
18 . Superman Returns
19 . Superman II
20 . Captain America: The Winter Soldier
21 . Jack the Giant Slayer
22 . Swordfish
23 . Captain America: Civil War
24 . Flushed Away
25 . Batman v Superman: Dawn of Justice
26 . Watchmen
27 . Iron Man
28 . The Shadow
29 . The Amazing Spider-Man
