<a href="https://colab.research.google.com/github/astitwa-agarwal12/Movie_Recommendation_System/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [94]:
movies_data = pd.read_csv('/content/movies.csv',error_bad_lines=False,engine="python")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


In [95]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [96]:
movies_data.shape

(4803, 24)

In [97]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [98]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [99]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [100]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [101]:
vectorizer = TfidfVectorizer()

In [102]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [103]:
print(feature_vectors)

  (0, 2432)	0.17272411194153
  (0, 7755)	0.1128035714854756
  (0, 13024)	0.1942362060108871
  (0, 10229)	0.16058685400095302
  (0, 8756)	0.22709015857011816
  (0, 14608)	0.15150672398763912
  (0, 16668)	0.19843263965100372
  (0, 14064)	0.20596090415084142
  (0, 13319)	0.2177470539412484
  (0, 17290)	0.20197912553916567
  (0, 17007)	0.23643326319898797
  (0, 13349)	0.15021264094167086
  (0, 11503)	0.27211310056983656
  (0, 11192)	0.09049319826481456
  (0, 16998)	0.1282126322850579
  (0, 15261)	0.07095833561276566
  (0, 4945)	0.24025852494110758
  (0, 14271)	0.21392179219912877
  (0, 3225)	0.24960162956997736
  (0, 16587)	0.12549432354918996
  (0, 14378)	0.33962752210959823
  (0, 5836)	0.1646750903586285
  (0, 3065)	0.22208377802661425
  (0, 3678)	0.21392179219912877
  (0, 5437)	0.1036413987316636
  :	:
  (4801, 17266)	0.2886098184932947
  (4801, 4835)	0.24713765026963996
  (4801, 403)	0.17727585190343226
  (4801, 6935)	0.2886098184932947
  (4801, 11663)	0.21557500762727902
  (4801, 1672

In [104]:
feature_vectors.shape

(4803, 17318)

In [105]:
similarity = cosine_similarity(feature_vectors)

In [106]:
print(similarity)

[[1.         0.07219487 0.037733   ... 0.         0.         0.        ]
 [0.07219487 1.         0.03281499 ... 0.03575545 0.         0.        ]
 [0.037733   0.03281499 1.         ... 0.         0.05389661 0.        ]
 ...
 [0.         0.03575545 0.         ... 1.         0.         0.02651502]
 [0.         0.         0.05389661 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02651502 0.         1.        ]]


In [107]:
print(similarity.shape)

(4803, 4803)


In [108]:
similarity[0]

array([1.        , 0.07219487, 0.037733  , ..., 0.        , 0.        ,
       0.        ])

In [109]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : avengers


In [110]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [111]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['The Avengers', 'Savages', 'Swingers']


In [112]:
close_match = find_close_match[0]
print(close_match)

The Avengers


In [113]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

16


In [114]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.03426340578061641), (1, 0.018757441743698592), (2, 0.03907993864609115), (3, 0.006602224357539788), (4, 0.05721539202804143), (5, 0.014194201691251133), (6, 0.02358797178187124), (7, 0.7860896884964055), (8, 0.008045023221038158), (9, 0.16210160555183875), (10, 0.07691564861356003), (11, 0.01217213686353538), (12, 0.013990444052447457), (13, 0.012631427434045384), (14, 0.1837336996264891), (15, 0.04563629684495581), (16, 0.9999999999999999), (17, 0.013383483902995971), (18, 0.02529414696558761), (19, 0.01188236224021718), (20, 0.11215733913329524), (21, 0.027050077660405823), (22, 0.007034788718083841), (23, 0.036653962075193565), (24, 0.01292652624563084), (25, 0.010727286350311038), (26, 0.4046969407600009), (27, 0.03121225816313765), (28, 0.06887119248461429), (29, 0.025483413379835257), (30, 0.11350883208096145), (31, 0.21487810271500662), (32, 0.029868095335032138), (33, 0.2505154038738609), (34, 0.0), (35, 0.036079460398325214), (36, 0.05009193086600237), (37, 0.0081898908

In [115]:
len(similarity_score)

4803

In [116]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(16, 0.9999999999999999), (7, 0.7860896884964055), (85, 0.4301532854607663), (26, 0.4046969407600009), (79, 0.3933653363061258), (126, 0.312803363203424), (511, 0.2892396085894662), (174, 0.28862963963238886), (64, 0.27464767891998554), (182, 0.27276411277152907), (129, 0.26928516313639983), (203, 0.25660973492915823), (33, 0.2505154038738609), (788, 0.24366990820486284), (46, 0.24006691472148445), (169, 0.23702484619175357), (38, 0.2338952010106937), (4759, 0.23084821219774054), (68, 0.22704403782296803), (31, 0.21487810271500662), (14, 0.1837336996264891), (782, 0.1825529075668662), (870, 0.1821588304668644), (101, 0.18018869067098506), (94, 0.16311290114551133), (9, 0.16210160555183875), (1294, 0.15229231204591692), (1192, 0.1517599526469107), (241, 0.15100480467438165), (4401, 0.1480526961044298), (2197, 0.14650796705575336), (1720, 0.14569980465005258), (713, 0.1452783854259603), (1740, 0.14444382118424323), (122, 0.14409292201469673), (242, 0.1411718728209748), (700, 0.138691786

In [117]:
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: The Winter Soldier
4 . Captain America: Civil War
5 . Iron Man 2
6 . Thor: The Dark World
7 . X-Men
8 . The Incredible Hulk
9 . X-Men: Apocalypse
10 . Ant-Man
11 . Thor
12 . X2
13 . X-Men: The Last Stand
14 . Deadpool
15 . X-Men: Days of Future Past
16 . Captain America: The First Avenger
17 . The Amazing Spider-Man 2
18 . The Image Revolution
19 . Iron Man
20 . Iron Man 3
21 . Man of Steel
22 . The Spirit
23 . Superman II
24 . X-Men: First Class
25 . Guardians of the Galaxy
26 . Batman v Superman: Dawn of Justice
27 . Serenity
28 . Spawn
29 . Teenage Mutant Ninja Turtles: Out of the Shadows


In [118]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()
#print(list_of_all_titles)
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : ultron
[(3445, 1.0), (628, 0.2560520241251187), (2448, 0.24413946448383017), (1922, 0.2273144369669861), (1440, 0.21617516288245153), (2671, 0.2068828335937562), (677, 0.195185080895996), (642, 0.18181653553613436), (456, 0.17673624751738706), (1373, 0.17613576603499784), (2578, 0.17559645096953638), (1181, 0.172280523450453), (599, 0.17165464967132063), (2536, 0.1696529568113476), (2898, 0.16307321131082025), (1094, 0.15863513625435166), (3750, 0.1581481329749639), (1459, 0.15675455258336973), (787, 0.15406560977044537), (2386, 0.1525124560386033), (1525, 0.14946729232229009), (2727, 0.14930138108244018), (3704, 0.14836952306423057), (1787, 0.14677330622344625), (1564, 0.14480419438623143), (480, 0.1446926388168821), (579, 0.14184529832364065), (586, 0.14058657813373748), (3130, 0.13928263454389586), (1106, 0.13736113194038874), (889, 0.13655779656530512), (156, 0.13602945701368332), (4419, 0.13425538044941637), (2922, 0.13224487858216133), (585, 0.1

In [119]:
import nltk
import re
import numpy as np

for i in range(len(combined_features)):
    combined_features[i] = combined_features[i].lower()
    combined_features[i] = re.sub(r'\W', ' ', combined_features[i])
    combined_features[i] = re.sub(r'\s+', ' ', combined_features[i])

In [120]:
print(combined_features)

0       action adventure fantasy science fiction cultu...
1       adventure fantasy action ocean drug abuse exot...
2       action adventure crime spy based on novel secr...
3       action crime drama thriller dc comics crime fi...
4       action adventure science fiction based on nove...
                              ...                        
4798    action crime thriller united states u2013mexic...
4799    comedy romance a newlywed couple s honeymoon i...
4800    comedy drama romance tv movie date love at fir...
4801     a new yorker in shanghai daniel henney eliza ...
4802    documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [121]:
nltk.download('punkt')
word2count = {}
for data in combined_features:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [122]:
print(word2count)

{'action': 1173, 'adventure': 871, 'fantasy': 441, 'science': 546, 'fiction': 540, 'culture': 20, 'clash': 13, 'future': 89, 'space': 89, 'war': 382, 'colony': 5, 'society': 17, 'enter': 7, 'the': 2018, 'world': 262, 'of': 962, 'pandora': 2, 'sam': 127, 'worthington': 8, 'zoe': 25, 'saldana': 15, 'sigourney': 22, 'weaver': 28, 'stephen': 130, 'lang': 11, 'michelle': 92, 'rodriguez': 34, 'james': 427, 'cameron': 65, 'ocean': 21, 'drug': 112, 'abuse': 39, 'exotic': 14, 'island': 57, 'east': 19, 'india': 18, 'trading': 3, 'company': 17, 'love': 437, 'one': 362, 's': 681, 'life': 294, 'at': 87, 'end': 31, 'begins': 41, 'johnny': 63, 'depp': 33, 'orlando': 16, 'bloom': 14, 'keira': 17, 'knightley': 17, 'stellan': 16, 'skarsg': 22, 'u00e5rd': 23, 'chow': 16, 'yun': 11, 'fat': 13, 'gore': 26, 'verbinski': 7, 'crime': 770, 'spy': 52, 'based': 328, 'on': 530, 'novel': 210, 'secret': 154, 'agent': 55, 'sequel': 60, 'mi6': 2, 'a': 1188, 'plan': 6, 'no': 223, 'escapes': 3, 'daniel': 102, 'craig': 

In [123]:
import heapq
freq_words = heapq.nlargest(100, word2count, key=word2count.get)

In [124]:
print(freq_words)

['drama', 'the', 'comedy', 'thriller', 'a', 'action', 'of', 'romance', 'adventure', 'crime', 'to', 'family', 's', 'is', 'you', 'john', 'michael', 'horror', 'science', 'fiction', 'in', 'on', 'it', 'and', 'fantasy', 'love', 'david', 'james', 'war', 'one', 'mystery', 'robert', 'relationship', 'for', 'based', 't', 'film', 'he', 'life', 'paul', 'new', 'world', 'will', 'music', 'animation', 'they', 'richard', 'your', 'tom', 'history', 'jason', 'kevin', 'woman', 'scott', 'no', 'independent', 'chris', 'peter', 'be', 'novel', 'can', 'man', 'story', 'lee', 'time', 'his', 'mark', 'steve', 'director', 'brother', 'are', 'there', 'christopher', 'has', 'never', 'jennifer', 'all', 'what', 'ben', 'martin', 'o', 'secret', 'murder', 'william', 'george', 'smith', 'was', 'sex', 'jones', 'bill', 'an', 'this', 'not', 'thomas', 'loss', 'father', 'j', 'that', 'stephen', 'patrick']


In [125]:
X = []
for data in combined_features:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)
X = np.asarray(X)

In [126]:
print(X)

[[0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [127]:
X.shape

(4803, 100)

In [128]:
similarity = cosine_similarity(X)

In [129]:
print(similarity)

[[1.         0.57207755 0.19069252 ... 0.         0.         0.        ]
 [0.57207755 1.         0.3        ... 0.12909944 0.         0.        ]
 [0.19069252 0.3        1.         ... 0.         0.15811388 0.        ]
 ...
 [0.         0.12909944 0.         ... 1.         0.         0.        ]
 [0.         0.         0.15811388 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [130]:
print(similarity.shape)

(4803, 4803)


In [131]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : avengers


In [132]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [133]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['The Avengers', 'Savages', 'Swingers']


In [134]:
close_match = find_close_match[0]
print(close_match)

The Avengers


In [135]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

16


In [136]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.38138503569823695), (1, 0.2), (2, 0.39999999999999997), (3, 0.10540925533894598), (4, 0.6), (5, 0.19069251784911848), (6, 0.25819888974716115), (7, 0.9128709291752769), (8, 0.11952286093343936), (9, 0.5163977794943223), (10, 0.4216370213557839), (11, 0.23904572186687872), (12, 0.282842712474619), (13, 0.25819888974716115), (14, 0.4601789933084223), (15, 0.3508232077228117), (16, 0.9999999999999999), (17, 0.31622776601683794), (18, 0.253546276418555), (19, 0.22360679774997896), (20, 0.21081851067789195), (21, 0.38729833462074176), (22, 0.11180339887498948), (23, 0.23904572186687872), (24, 0.21081851067789195), (25, 0.1414213562373095), (26, 0.7171371656006361), (27, 0.4216370213557839), (28, 0.5590169943749475), (29, 0.38729833462074176), (30, 0.17541160386140586), (31, 0.6708203932499369), (32, 0.3), (33, 0.6324555320336759), (34, 0.0), (35, 0.5163977794943223), (36, 0.45643546458763845), (37, 0.11180339887498948), (38, 0.4780914437337574), (39, 0.4780914437337574), (40, 0.11952

In [137]:
len(similarity_score)

4803

In [138]:

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(16, 0.9999999999999999), (7, 0.9128709291752769), (26, 0.7171371656006361), (85, 0.7171371656006361), (511, 0.7171371656006361), (56, 0.7071067811865476), (1001, 0.7), (31, 0.6708203932499369), (174, 0.6674238124719147), (3494, 0.6674238124719147), (1990, 0.6454972243679029), (33, 0.6324555320336759), (111, 0.6324555320336759), (182, 0.6324555320336759), (79, 0.6139406135149205), (4, 0.6), (169, 0.6), (183, 0.6), (400, 0.6), (1303, 0.6), (47, 0.5976143046671968), (68, 0.5976143046671968), (94, 0.5976143046671968), (1155, 0.5976143046671968), (70, 0.5916079783099616), (2444, 0.5720775535473555), (51, 0.565685424949238), (495, 0.565685424949238), (28, 0.5590169943749475), (158, 0.5590169943749475), (466, 0.5590169943749475), (854, 0.5590169943749475), (1326, 0.5590169943749475), (1650, 0.5590169943749475), (2129, 0.5590169943749475), (4117, 0.5590169943749475), (1192, 0.5533985905294664), (249, 0.5477225575051662), (256, 0.5477225575051662), (3089, 0.5477225575051662), (4187, 0.5477225

In [139]:

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: Civil War
4 . Captain America: The Winter Soldier
5 . X-Men
6 . Star Trek Beyond
7 . Street Fighter: The Legend of Chun-Li
8 . Iron Man 3
9 . The Incredible Hulk
10 . Beastmaster 2: Through the Portal of Time
11 . The Empire Strikes Back
12 . X-Men: The Last Stand
13 . Transformers
14 . Ant-Man
15 . Iron Man 2
16 . John Carter
17 . Captain America: The First Avenger
18 . The Hunger Games: Catching Fire
19 . Divergent
20 . Star Trek: Generations
21 . Star Trek Into Darkness
22 . Iron Man
23 . Guardians of the Galaxy
24 . Spy Kids 3-D: Game Over
25 . Wild Wild West
26 . Damnation Alley
27 . Pacific Rim
28 . Journey 2: The Mysterious Island
29 . Jurassic World


In [140]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : ultron
Movies suggested for you : 

1 . Platoon
2 . Rabbit Hole
3 . 5 Days of War
4 . Flight of the Intruder
5 . The Marine
6 . Clear and Present Danger
7 . 1911
8 . Elite Squad
9 . White Squall
10 . The Painted Veil
11 . Seven Samurai
12 . Flight of the Phoenix
13 . Letters from Iwo Jima
14 . Training Day
15 . Valley of the Heart's Delight
16 . Kickboxer: Vengeance
17 . Alexander
18 . Green Zone
19 . Saving Private Ryan
20 . Top Gun
21 . The Conversation
22 . The Business of Fancydancing
23 . The Last Samurai
24 . Dragon Blade
25 . The Messenger: The Story of Joan of Arc
26 . The Impossible
27 . Pound of Flesh
28 . The Kentucky Fried Movie
29 . United 93
